name: Github Actions Demo
on:
 push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
 pull_request:
    branches:
      - main
 schedule:
    - cron: "15 6 * * 0"  # Every Sunday at 06:15 UTC
 workflow_dispatch:
    inputs:
      target_environment:
        description: "Which GitHub Environment to run against"
        type: environment
        required: true
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Triggering event and branch nameðŸŽ‰
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Branch: ${{github.ref_name}}"
      - name: List repository files
        run: |
          tree .
  Test:
    runs-on: ubuntu-latest
    needs: Build
    environment: Test
    if: ${{ github.event_name == 'workflow_dispatch'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Triggering event and branch nameðŸŽ‰
        run: |
          echo "Testing..."
  Load-Test:
    runs-on: ubuntu-latest
    needs: Build
    environment: Load-Test
    if: ${{ github.event_name == 'workflow_dispatch'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Triggering event and branch nameðŸŽ‰
        run: |
          echo "Testing..."
          sleep 15
  Production:
    runs-on: ubuntu-latest
    environment: Production
    needs: [Test, Load-Test]
        # "validate": only run this job if the workflow was manual AND Production was selected
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.target_environment == 'Production' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Step 1
        run: |
          echo "Step 1 deploying..."
          sleep 10
      - name: Step 2
        run: |
          echo "Step 2 deploying..."
          sleep 10
      - name: Step 3
        run: |
          echo "Step 3 deploying..."
          sleep 10
      - name: Step 4
        run: |
          echo "Step 4 deploying..."
          sleep 10
      - name: Step 5
        run: |
          echo "Step 5 deploying..."
          sleep 10
 
